# -*- coding: utf-8 -*-
# Batch 5: "looked" — Book 2 multi-look paragraphs + singles
EDITS = [
# --- multi-look paragraphs ---
(2, 174, "and the look on her face was the look of a mother", "and the look on her face was that of a mother"),
(2, 459, "He looked the way Gormund had looked after the dragon fight, the gray, washed-out pallor", "He wore the same gray Gormund had worn after the dragon fight, the washed-out pallor"),
(2, 578, "Gormund looked at the ladder. Looked at Cain, unconscious in the cart. Looked at the twenty-foot climb to the deck.", "Gormund looked at the ladder. At Cain, unconscious in the cart. At the twenty-foot climb to the deck."),
(2, 1029, "He sat up, looked at Cain, looked at the supplies, looked at the room.", "He sat up, looked at Cain, at the supplies, at the room."),
(2, 1225, "They looked at her. She looked at them. A short woman", "They stared at her. She stared back. A short woman"),
(2, 1420, "He looked at the man. At the wagon. At Carina’s hand on his sleeve.", "His gaze moved to the man, the wagon, Carina’s hand on his sleeve."),
(2, 1437, "The man looked confused. Middle-aged, weathered,", "The man’s face went blank with confusion. Middle-aged, weathered,"),
(2, 1654, "Billy looked at Jane. Jane looked at Billy. The silence stretched.", "Billy looked at Jane. Jane held it. The silence stretched."),
(2, 1848, "He paused. Looked at the line. Looked at Uthesia.", "He paused. Looked at the line, then at Uthesia."),
(2, 1874, "He looked at Cain. Looked him up and down.", "He looked Cain up and down."),
(2, 1962, "She was looking at the ground. At her own body,", "She was facing the ground. At her own body,"),
(2, 2190, "Cain looked at the line. Looked at Muse. Wrote her name.", "Cain looked at the line. Then at Muse. Wrote her name."),
(2, 2203, "Each of them looking at the girl in her arms with an expression that told its own story.", "Each of them fixed on the girl in her arms with an expression that told its own story."),
(2, 2257, "He looked at the vial. Looked at Carina, on the bed,", "He looked at the vial. At Carina, on the bed,"),
(2, 2353, "Carina looked at the dwarf. Looked at the group. Held up her stump.", "Carina looked at the dwarf. At the group. Held up her stump."),
(2, 2487, "She looked at Uthesia’s back. Looked at her left arm, the stump,", "She looked at Uthesia’s back. At her own left arm, the stump,"),
(2, 2577, "Gormund looked at Cain. Cain looked back.", "Gormund stared at Cain. Cain stared back."),
(2, 2636, "Gormund looked at the horde. Looked at the Gallows Horn standing beside him, seven heads’ worth of stolen abilities ready to deploy. Looked at Cain and Carina,", "Gormund looked at the horde. At the Gallows Horn standing beside him, seven heads’ worth of stolen abilities ready to deploy. At Cain and Carina,"),
(2, 3776, "a book that looked different from the others", "a book that didn’t match the others"),
(2, 3981, "He looked around the circle.", "His eye traveled the circle."),
(2, 4495, "She wasn’t looking at Carina. She was looking at the ground, her shoulders pulled inward,", "She wasn’t looking at Carina. She was studying the ground, her shoulders pulled inward,"),
(2, 4587, "He looked up. “Carina? Well, look who it is.", "His head came up. “Carina? Well, look who it is."),
# --- Book 2 singles ---
(2, 14, "He looked at the sleeping pile by the hearth.", "He turned to the sleeping pile by the hearth."),
(2, 62, "He looked at the window. The shutters. The wall.", "His eye went to the window. The shutters. The wall."),
(2, 91, "She looked up from the map.", "She raised her eyes from the map."),
(2, 138, "She looked up at Yoo with the expression of someone who had been delivering bad news", "She greeted Yoo with the expression of someone who had been delivering bad news"),
(2, 153, "the first fraction it had eased in what looked like months", "the first fraction it had eased in what must have been months"),
(2, 163, "The precedent would destroy us.” He looked at her.", "The precedent would destroy us.” His eyes came up to her."),
(2, 265, "Uthesia looked at him. The flame elemental flickered between them,", "Uthesia’s eye stayed on him. The flame elemental flickered between them,"),
(2, 414, "He set the ledger back down and looked around the tent, surveying the organized rows", "He set the ledger back down and surveyed the tent, the organized rows,"),
(2, 436, "Carina looked back at Jane, her chin lifting,", "Carina faced Jane, her chin lifting,"),
(2, 554, "Both of them looked at her. She was still on her knees", "Both of them turned to her. She was still on her knees"),
(2, 556, "Gormund looked at her. At her hands, steady on Cain’s chest. At the blindfold, the composure, the certainty.", "Gormund took her measure. Her hands, steady on Cain’s chest. The blindfold, the composure, the certainty."),
(2, 603, "She looked at the glass panel. Took a step back.", "She sized up the glass panel. Took a step back."),
(2, 627, "Carina looked at the ship. The frozen hull,", "Carina considered the ship. The frozen hull,"),
(2, 942, "The man looked at them, at the hold, at the wreckage.", "His gaze swept them, the hold, the wreckage."),
(2, 1132, "He looked at her. The grin.", "He turned to her. The grin."),
(2, 1153, "Billy stopped. Looked at the empty square.", "Billy stopped. Took in the empty square."),
(2, 1158, "He looked at Carina. “Tell you what.", "He cocked his head at Carina. “Tell you what."),
(2, 1274, "She looked at the throne room. At the knights,", "She surveyed the throne room. At the knights,"),
(2, 1284, "Dantalion looked at Elizabeth.", "Dantalion faced Elizabeth."),
(2, 1308, "The tube in his arm pulled taut and he looked at it, considered it, pulled it free.", "The tube in his arm pulled taut and he considered it, then pulled it free."),
(2, 1336, "Cain looked around the bridge.", "Cain scanned the bridge."),
(2, 1339, "Cain looked at the console. Buttons. Levers.", "Cain studied the console. Buttons. Levers."),
(2, 1355, "Cain looked at her. “Thank you. For coming with me.", "Cain dipped his head to her. “Thank you. For coming with me."),
(2, 1392, "Cain looked at them.", "Cain took a moment."),
(2, 1429, "He looked at her. “But I’m trusting you.", "His eyes slid to her. “But I’m trusting you."),
(2, 1481, "Fafnir looked at Ghisara. “And you?”", "Fafnir turned to Ghisara. “And you?”"),
(2, 1524, "Removed his hand. Looked at the remaining bandits,", "Removed his hand. Faced the remaining bandits,"),
(2, 1555, "Looked at Barbatos over the rim.", "Regarded Barbatos over the rim."),
(2, 1564, "Barbatos looked at the dried plant.", "Barbatos stared at the dried plant."),
(2, 1583, "He looked at Barbatos over the blade.", "He held Barbatos’s eyes over the blade."),
(2, 1624, "Dantalion looked at his daughter. The picture of composed aristocratic youth,", "Dantalion considered his daughter. The picture of composed aristocratic youth,"),
(2, 1632, "She looked at him for a long moment. Then she turned and walked", "She regarded him for a long moment. Then she turned and walked"),
(2, 1679, "Billy looked at her. The firelight danced in his golden eyes.", "Billy’s eyes settled on her. The firelight danced in them."),
(2, 1695, "four replacements.” He looked at them.", "four replacements.” He faced them."),
(2, 1715, "He stopped. Looked around. White in every direction,", "He stopped. Turned a circle. White in every direction,"),
(2, 1719, "Looked at the ground beneath his boots.", "Studied the ground beneath his boots."),
(2, 1811, "He looked at Gormund.", "He turned to Gormund."),
(2, 1815, "Fafnir looked at him. The Chaptermaster’s eyes were sharp,", "Fafnir said nothing for a moment. The Chaptermaster’s eyes were sharp,"),
(2, 1822, "He stopped pacing. Looked at them.", "He stopped pacing."),
(2, 1830, "Uthesia looked at Gormund. The recognition hit them simultaneously,", "Uthesia found Gormund’s eyes. The recognition hit them simultaneously,"),
(2, 1959, "She looked up at Carina.", "She peered up at Carina."),
(2, 2205, "Then she looked at the party again. Her ears swiveled forward,", "Then she turned back to the party. Her ears swiveled forward,"),
(2, 2211, "He looked at the party, at Carina on the bed, closed his mouth,", "He took in the party, Carina on the bed, closed his mouth,"),
(2, 2260, "He set the empty vial on the table beside his bed. Looked at Carina.", "He set the empty vial on the table beside his bed. Found Carina with his eye."),
(2, 2292, "Looked up at Uthesia.", "Glanced up at Uthesia."),
(2, 2320, "The party looked at each other.", "The party traded glances."),
(2, 2327, "The door closed behind him and Carina looked around at the group.", "The door closed behind him and Carina rounded on the group."),
(2, 2329, "Gormund looked at her stump.", "Gormund nodded at her stump."),
(2, 2342, "She looked at her stump again. At the group. At Fafnir.", "Her eyes dropped to the stump again. To the group. To Fafnir."),
(2, 2415, "Fafnir looked between them.", "Fafnir’s eyes moved between them."),
(2, 2626, "He reached the base and looked at the dismantled knights, then at Cain and Carina,", "He reached the base and took in the dismantled knights, then Cain and Carina,"),
(2, 2681, "Cain looked at the army. At the city behind it,", "Cain studied the army. At the city behind it,"),
(2, 2707, "He looked at them grateful and skeptical simultaneously.", "He took them in, grateful and skeptical simultaneously."),
(2, 2722, "He looked at the five of them.", "He addressed the five of them."),
(2, 2761, "Cain looked at Carina. At Uthesia. Two of his three frontliners,", "Cain considered Carina, then Uthesia. Two of his three frontliners,"),
(2, 3006, "He looked back. A column of light was rising", "He glanced back. A column of light was rising"),
(2, 3086, "He looked at the Death Knights standing at her command.", "He eyed the Death Knights standing at her command."),
(2, 3100, "Dantalion looked at her. The grape paused mid-chew.", "The grape paused mid-chew."),
(2, 3310, "He looked at Carina. The girl was still catching her breath,", "His eyes went to Carina. The girl was still catching her breath,"),
(2, 3322, "He looked between them.", "He followed the exchange."),
(2, 3326, "Carina lingered. She looked at Fafnir.", "Carina lingered. Her eyes found Fafnir."),
(2, 3439, "Cain looked between them. The resemblance was immediate,", "Cain’s eye moved between them. The resemblance was immediate,"),
(2, 3475, "She looked like she wanted to argue. The fighter in her,", "Everything in her face wanted to argue. The fighter in her,"),
(2, 3513, "The guard looked between them.", "The guard glanced from one to the other."),
(2, 3608, "He looked at the girl across from him.", "He studied the girl across from him."),
(2, 3658, "Gormund looked at Bloody Thunder in its holster.", "Gormund rested a hand on Bloody Thunder in its holster."),
(2, 3755, "Uthesia took the book, opened it. Looked at the page.", "Uthesia took the book, opened it. Scanned the page."),
(2, 3763, "Uthesia looked at Muse. “You’re the closest thing we have to a magic expert.”", "Uthesia deferred to Muse. “You’re the closest thing we have to a magic expert.”"),
(2, 3813, "The room was quiet. The party looked at each other.", "The room was quiet. The party exchanged blank glances."),
(2, 3893, "She stood back. Looked at the four maps, the four objectives,", "She stood back. Took stock of the four maps, the four objectives,"),
(2, 3914, "He sat up in the coffin. Looked at his hands. Gray skin,", "He sat up in the coffin. Examined his hands. Gray skin,"),
(2, 3932, "He looked at the Merchant. The smile was back.", "He faced the Merchant. The smile was back."),
(2, 4035, "He looked at Muse.", "He turned to Muse."),
(2, 4192, "Inarus straightened, catching his breath. He looked around.", "Inarus straightened, catching his breath. He scanned the dark."),
(2, 4274, "Uthesia looked at the revolver. The bore was wide.", "Uthesia measured the revolver. The bore was wide."),
(2, 4323, "He looked at her. The ginger beard shifted", "The ginger beard shifted"),
]
