# -*- coding: utf-8 -*-
# Batch 3: Book 2 remaining "something" — deletes of double-taps, rewrites for specificity
EDITS = [
(2, 21, "Something in his body, his blood, his composition, refused to accept the conclusion", "His body, his blood, his composition refused to accept the conclusion"),
(2, 116, "and yet something about her presence, the stillness behind that cracked mask", "and yet her presence, the stillness behind that cracked mask"),
(2, 120, "outsourcing your combat to something you’d constructed", "outsourcing your combat to a machine you’d constructed"),
(2, 180, "turned the careful insulation into something permeable and useless", "turned the careful insulation permeable and useless"),
(2, 320, "Holding something heavy enough that the rope protested each arc", "Holding a load heavy enough that the rope protested each arc"),
(2, 330, "replaced by something older and simpler that operated on contact", "replaced by an older, simpler engine that operated on contact"),
(2, 350, "a sound that was part impact and part breakage, something inside her cracking audibly", "a sound that was part impact and part breakage, bone cracking audibly"),
(2, 353, "The flame elemental’s light warped, bent, became something unreliable.", "The flame elemental’s light warped, bent, became unreliable."),
(2, 546, "the unfocused look replaced by something sharp and certain", "the unfocused look replaced by a sharp certainty"),
(2, 627, "the promise of something valuable locked behind technology", "the promise of valuables locked behind technology"),
(2, 739, "turned the air between the walls into something lethal", "turned the air between the walls lethal"),
(2, 831, "the fibers separated by something sharp and fast", "the fibers separated by an edge, sharp and fast"),
(2, 981, "the whisper of flame consuming something thin and prepared", "the whisper of flame consuming a thin, prepared sheet"),
(2, 990, "The voice was quieter now, closer to something private.", "The voice was quieter now, closer to confession."),
(2, 1056, "the steady, repetitive motion that turned raw material into something useful", "the steady, repetitive motion that turned raw material useful"),
(2, 1246, "It rearranged itself into something more conversational, the grin of a man", "It rearranged itself toward conversation, the grin of a man"),
(2, 1254, "the grin settling into something more instructional", "the grin settling into instruction"),
(2, 1284, "The grin was gone, replaced by something colder, more efficient.", "The grin was gone, replaced by a colder efficiency."),
(2, 1303, "Something else, something steady and white, emanating from flat panels", "Something else, steady and white, emanating from flat panels"),
(2, 1381, "still processing something beyond their frame of reference", "still processing what sat beyond their frame of reference"),
(2, 1410, "died in his throat, replaced by something more immediate", "died in his throat, replaced by more immediate business"),
(2, 1415, "running from one thing and freshly arrived at something worse", "running from one thing and freshly arrived at worse"),
(2, 1421, "Something about being lucky she was pretty, or something close to it", "A remark about being lucky she was pretty, or close to it"),
(2, 1448, "rose and began moving in a rhythm that meant something had caught her attention in a way that transcended rational thought", "rose and began moving in a rhythm that meant her attention had been caught in a way that transcended rational thought"),
(2, 1471, "Something else. Something the Tablet described and the stories promised", "Something else. The thing the Tablet described and the stories promised"),
(2, 1530, "A pleasant tune, something old, something he’d picked up centuries ago", "A pleasant tune, old, picked up centuries ago"),
(2, 1592, "the line of his shoulders carrying something just shy of defeat", "the line of his shoulders set just shy of defeat"),
(2, 1618, "Something shifted behind Elizabeth’s eyes.", "Behind Elizabeth’s eyes, a recalculation."),
(2, 1634, "Carina felt something she hadn’t expected", "Carina felt an unfamiliar flutter"),
(2, 1645, "It was something harder, set.", "It was harder, set."),
(2, 1752, "the sound of soldiers responding to something unexpected at their entrance", "the sound of soldiers responding to trouble at their entrance"),
(2, 1932, "patience was not something the House of Murder had ever prioritized", "patience was not a virtue the House of Murder had ever prioritized"),
(2, 2229, "the distance he always maintained when something emotional was developing", "the distance he always maintained when emotions ran high"),
(2, 2245, "Something shifted in her expression.", "Her expression shifted."),
(2, 2332, "the disgust draining away, leaving something more honest underneath", "the disgust draining away, leaving what was more honest underneath"),
(2, 2357, "the expression on her face was something none of them had seen before", "the expression on her face was one none of them had seen before"),
(2, 2457, "restoring something psychological that rest alone couldn’t", "restoring a confidence that rest alone couldn’t"),
(2, 2477, "The warmth receded, replaced by something more careful, the tone she used", "The warmth receded, replaced by a more careful tone, the one she used"),
(2, 2779, "waiting for someone who had something worthwhile to write within", "waiting for someone with work worth recording within"),
(2, 2793, "The formal liturgy giving way to something quieter.", "The formal liturgy giving way to plainer words."),
(2, 3077, "He must have looked like something out of their nightmares", "He must have been a sight out of their nightmares"),
(2, 3182, "The expression on her face was something Dantalion had never seen before.", "The expression on her face was one Dantalion had never seen before."),
(2, 3263, "the regular rhythm of living movement corrupting into something else", "the regular rhythm of living movement corrupting, going wrong"),
(2, 3321, "She grumbled something under her breath that was probably not complimentary.", "She grumbled under her breath, words that were probably not complimentary."),
(2, 3510, "her expression shifting from tired to alert at something in his tone", "her expression shifting from tired to alert at what she heard in his tone"),
(2, 3561, "The rawness in his voice was something she’d never heard from him.", "The rawness in his voice was nothing she’d ever heard from him."),
(2, 3584, "Underneath the road dust and the sweat, something floral, something specific.", "Underneath the road dust and the sweat, a floral note, specific."),
(2, 3817, "having just held something worth more than his annual earnings", "having just held an object worth more than his annual earnings"),
(2, 3819, "his posture shifting from panicked student to something approaching authority", "his posture shifting from panicked student toward authority"),
(2, 3911, "the softness of the living man replaced by something harder", "the softness of the living man replaced by a harder cast"),
(2, 3941, "but had been managed into something approaching tolerable", "but had been managed into a tolerable shape"),
(2, 3958, "the streets of Solarspire becoming something approaching known territory", "the streets of Solarspire becoming known territory, or close to it"),
(2, 3988, "heading for something none of them could follow him to", "heading for a place none of them could follow him to"),
(2, 4020, "the measured eladrin giving way to something underneath that had been held in check for months", "the measured eladrin giving way to what had been held in check for months"),
(2, 4082, "and the empty evening blurring into something tolerable", "and the empty evening blurring until they were bearable"),
(2, 4141, "the rapid-fire percussion of something being torn into fragments", "the rapid-fire percussion of wood being torn into fragments"),
(2, 4323, "his mouth formed something between a grin and a grimace", "his mouth formed half a grin, half a grimace"),
(2, 4346, "a calm, pure white landscape that looked like something a painter would compose and title", "a calm, pure white landscape a painter might compose and title"),
(2, 4495, "her posture carrying something Carina had never seen in her mother’s body language before", "her posture carrying a quality Carina had never seen in her mother’s body language before"),
(2, 4551, "the combinations breaking from their expected sequences into something improvised and dangerous", "the combinations breaking from their expected sequences, improvised and dangerous"),
]
