# -*- coding: utf-8 -*-
# Batch 2: Book 1 remaining "something" — deletes of double-taps, rewrites for specificity
EDITS = [
(1, 10, "The smell of old leather and metal polish and something faintly animal beneath it", "The smell of old leather and metal polish and a faint animal note beneath it"),
(1, 12, "the creak of his armor as he sat on something, probably the low stone wall", "the creak of his armor as he sat, probably on the low stone wall"),
(1, 54, "She heard something heavy set down on the table, probably a ledger from the sound of it", "She heard weight settle on the table, probably a ledger from the sound of it"),
(1, 63, "the slow intake of a man about to say something he’d rehearsed", "the slow intake of a man about to say words he’d rehearsed"),
(1, 95, "people had walked this way often enough to flatten the ground into something resembling a route", "people had walked this way often enough to flatten the ground into the rough shape of a route"),
(1, 165, "Carina asked with something between amusement and genuine curiosity", "Carina asked, halfway between amusement and genuine curiosity"),
(1, 201, "enough heat to thaw the waterskin into something they could pass around", "enough heat to thaw the waterskin enough to pass around"),
(1, 224, "Carina saw the smoke first because Carina was the only one looking for something interesting", "Carina saw the smoke first because Carina was the only one hungry for anything interesting"),
(1, 275, "The rocky, sparse ground gave way to something slightly softer, frozen mud", "The rocky, sparse ground gave way to slightly softer ground, frozen mud"),
(1, 282, "the scattered formation of a long day’s travel contracting into something more purposeful", "the scattered formation of a long day’s travel contracting, turning purposeful"),
(1, 287, "Not relief, not concern. Something between the two.", "Not relief, not concern. Caught between the two."),
(1, 309, "a deliberateness that felt like being shown something she was supposed to already understand", "a deliberateness that felt like being shown a lesson she was supposed to already understand"),
(1, 345, "Something moved behind her eyes.", "A weight moved behind her eyes."),
(1, 351, "as if silence had become something people couldn’t afford", "as if silence had become an indulgence people couldn’t afford"),
(1, 362, "voices in the cadence of people managing something large and complicated", "voices in the cadence of people managing a large, complicated operation"),
(1, 370, "or the turning of a page, something written being consulted", "or the turning of a page, a written record being consulted"),
(1, 374, "the hoarseness softened slightly into something more measured", "the hoarseness softened slightly into a more measured register"),
(1, 466, "probably to press, but something in the flat finality of those two words stopped her", "probably to press, but the flat finality of those two words stopped her"),
(1, 474, "But Muse felt something in it, something small and probably involuntary", "But Muse felt a give in it, something small and probably involuntary"),
(1, 523, "Something between surprise and something softer that the eladrin shut down almost immediately", "Something between surprise and a softness the eladrin shut down almost immediately"),
(1, 528, "the air between them felt like something other than survival", "the air between them felt like more than survival"),
(1, 553, "and something in her shoulders eased that she hadn’t realized she’d been holding", "and a weight in her shoulders eased that she hadn’t realized she’d been holding"),
(1, 678, "she held the moment like something fragile", "she held the moment like spun glass"),
(1, 752, "nothing about killing something this big could be elegant", "nothing about killing a beast this big could be elegant"),
(1, 759, "men who’d just killed something big enough that the reality of it needed a moment to arrive", "men who’d just killed an animal big enough that the reality of it needed a moment to arrive"),
(1, 802, "carried the weight of something he’d been without for a long time", "carried the weight of what he’d been without for a long time"),
(1, 805, "The meat was riddled with something wrong.", "The meat was riddled with wrongness."),
(1, 844, "softened his face into something almost warm", "softened his face toward warmth"),
(1, 881, "felt something cold settle into a place behind his ribs", "felt a coldness settle into a place behind his ribs"),
(1, 895, "his mouth twisted into something between amusement and distaste", "his mouth twisted, amusement and distaste in equal parts"),
(1, 924, "heard something behind it. A voice, thin and high", "heard a sound behind it. A voice, thin and high"),
(1, 972, "Gormund watched her from the corner and felt something complicated.", "Gormund watched her from the corner, and what he felt was complicated."),
(1, 1063, "her voice had reassembled itself into something precise and operational", "her voice had reassembled itself, precise and operational"),
(1, 1142, "Something caught, something shifted, and Cain made a sound through his teeth", "Steel caught, armor shifted, and Cain made a sound through his teeth"),
(1, 1151, "released its smell into the corridor, sharp and sweet, the unmistakable scent of something worth investigating", "released its smell into the corridor, sharp and sweet, unmistakably worth investigating"),
(1, 1157, "because making sound on stone was something she’d trained out of herself", "because making sound on stone was a habit she’d trained out of herself"),
(1, 1193, "Cain’s expression shifted from tension to something harder to read", "Cain’s expression shifted from tension to a stillness harder to read"),
(1, 1240, "and something in the quality of the sound was wrong", "and the quality of the sound was wrong"),
(1, 1306, "for the first time there was something in his voice that wasn’t amusement or authority", "for the first time there was a note in his voice that wasn’t amusement or authority"),
(1, 1310, "the expression of a man seeing something genuinely novel", "the expression of a man seeing a genuine novelty"),
(1, 1365, "the way a child looks at something interesting pinned under glass", "the way a child studies an insect pinned under glass"),
(1, 1375, "It was something stripped and raw, the voice of the man he’d buried under the vow", "It came out stripped and raw, the voice of the man he’d buried under the vow"),
(1, 1396, "It was something resembling molten slag, like a forge filled with molten metals", "It was close to molten slag, like a forge filled with molten metals"),
(1, 1403, "spinning uselessly, and felt something shift in his assessment of the situation", "spinning uselessly, and felt his assessment of the situation shift"),
(1, 1425, "something in her left wrist snapped with a sound she felt more than heard", "a bone in her left wrist snapped with a sound she felt more than heard"),
(1, 1460, "together had added up to something the beast could feel", "together had added up to a total the beast could feel"),
(1, 1497, "Something passed between them that wasn’t words", "What passed between them wasn’t words"),
(1, 1581, "turning the cold around her hands into something the dome couldn’t touch", "turning the cold around her hands into a heat the dome couldn’t touch"),
(1, 1654, "Something wet on the stone, she couldn’t tell if it was water or blood", "Wetness on the stone, she couldn’t tell if it was water or blood"),
(1, 1712, "the stunned silence of something no one expected", "the stunned silence of news no one expected"),
(1, 2153, "Something moved behind his eyes that might have been hatred or might have been something more complicated", "What moved behind his eyes might have been hatred or might have been more complicated"),
(1, 1789, "the beginning of a word, something gentle, something meant to ease her down", "the beginning of a word, gentle, meant to ease her down"),
(1, 1804, "broken by the dome into something pale and thin", "broken by the dome into pale, thin light"),
(1, 1809, "the sound of a body being asked to do something it was physically not designed to survive", "the sound of a body being pushed past what it was designed to survive"),
(1, 1821, "her head resting on something folded and soft", "her head resting on a folded bundle, soft"),
(1, 1821, "someone had layered something between her and the floor", "someone had layered bedding between her and the floor"),
(1, 1848, "turning the campsite into something closer to early winter than the late spring", "turning the campsite closer to early winter than the late spring"),
(1, 1896, "replaced by something colder and more careful", "replaced by a colder, more careful light"),
(1, 1922, "the exhaustion caught it and turned it into something closer to a sigh", "the exhaustion caught it and turned it into more sigh than laugh"),
(1, 1940, "left behind something looser, something closer to the man underneath the title", "left behind a looser posture, closer to the man underneath the title"),
(1, 1996, "Something in his expression shifted from disbelief to something harder to name", "His expression shifted from disbelief to a place harder to name"),
(1, 2013, "the tone of a woman stating something so fundamentally non-negotiable", "the tone of a woman stating a fact so fundamentally non-negotiable"),
(1, 2106, "The third she couldn’t crack, something internal had rusted shut from the cold", "The third she couldn’t crack, its insides rusted shut from the cold"),
(1, 2179, "the pain was background noise by now, something his body had accepted as part of the landscape", "the pain was background noise by now, accepted as part of the landscape"),
(1, 2240, "the grip of a woman holding onto something because letting go meant accepting something she wasn’t ready to accept", "the grip of a woman holding on, because letting go meant accepting what she wasn’t ready to accept"),
(1, 2275, "He was leaning against a doorframe, looking at something inside that Muse couldn’t see", "He was leaning against a doorframe, fixed on whatever was inside it"),
(1, 2356, "a freeze deep enough to turn timber into something closer to stone", "a freeze deep enough to turn timber nearly to stone"),
(1, 2533, "because the admission had cost something visible in the way she held her hands near the flames", "because the admission had cost her, visibly, in the way she held her hands near the flames"),
(1, 2548, "From something older, something wired into the base of his spine", "From something older, wired into the base of his spine"),
(1, 2629, "the tone shifted, something appreciative in it that Carina’s dimming instincts still registered as wrong", "the tone shifted, an appreciation in it that Carina’s dimming instincts still registered as wrong"),
(1, 2783, "and there was something in her voice that was almost playful, an edge of warmth that the firelight brought out", "and her voice was almost playful, an edge of warmth the firelight brought out"),
(1, 2827, "the reports echoing off something close", "the reports echoing off walls close by"),
(1, 2836, "pressing something hot against the raw tissue", "pressing hot metal against the raw tissue"),
(1, 2876, "The grin faded into something plain, matter-of-fact.", "The grin faded, plain and matter-of-fact."),
]
