# -*- coding: utf-8 -*-
# Batch 4: "looked" — multi-look paragraphs (double-taps) + Book 1 singles
EDITS = [
# --- multi-look paragraphs, Book 1 ---
(1, 60, "he wasn’t looking at Aldrich. Probably looking at his own hands.", "he wasn’t facing Aldrich. Probably facing his own hands."),
(1, 523, "Gormund looked at her. Then at Uthesia, who was looking at Muse with an expression he couldn’t quite read.", "Gormund glanced at her. Then at Uthesia, whose eye was fixed on Muse with an expression he couldn’t quite read."),
(1, 884, "The guards exchanged a look. One of them, the ranking officer by the marks on his armor, looked the party over.", "The guards exchanged a glance. One of them, the ranking officer by the marks on his armor, sized the party up."),
(1, 895, "He looked up. His eyes moved over the party the way one looks at furniture being delivered.", "He glanced up. His eyes moved over the party the way one inspects furniture being delivered."),
(1, 916, "He looked at the crest on the wall, the heraldry of heroes,", "His eye went to the crest on the wall, the heraldry of heroes,"),
(1, 966, "Carina looked at him. Genuinely confused, the look of being told water flows uphill.", "Carina stared at him. Genuinely confused, the face of being told water flows uphill."),
(1, 1093, "Cain said, looking at the charcoal map. Then he looked at his own shoulders.", "Cain said, studying the charcoal map. Then he considered his own shoulders."),
(1, 1105, "Uthesia looked at her. Carina looked back.", "Uthesia held her gaze. Carina gave it back."),
(1, 1203, "He looked at Carina. Looked at Andromalius. Looked at Muse.", "His eye went from Carina to Andromalius to Muse."),
(1, 1305, "He looked at Carina. The blood on her knuckles.", "He turned to Carina. The blood on her knuckles."),
(1, 1308, "But you.” He looked back at Carina.", "But you.” His gaze came back to Carina."),
(1, 1323, "He should have looked beaten. He should have looked like a man whose keep was in ruins above him", "He should have looked beaten. Like a man whose keep was in ruins above him"),
(1, 1407, "He looked at it. He looked at the dragon.", "He looked at it. Then at the dragon."),
(1, 1470, "He looked at the blood on the floor. Looked at the wound he couldn’t see but could feel,", "At the blood on the floor. At the wound he couldn’t see but could feel,"),
(1, 1896, "Barbatos looked at Leo, looked at Gale, and whatever calculation", "Barbatos glanced from Leo to Gale, and whatever calculation"),
(1, 1917, "Leo looked at her. At the woman", "Leo studied her. At the woman"),
(1, 2032, "and looking at their faces wouldn’t change either of those facts", "and studying their faces wouldn’t change either of those facts"),
(1, 2138, "The lord looked at it. Looked at Cain.", "The lord looked at it. Then at Cain."),
(1, 2204, "Cain looked at them. At Gormund,", "Cain took stock of them. At Gormund,"),
(1, 2369, "He looked at the fire. Looked at his hands in the light of it.", "He looked at the fire. At his hands in the light of it."),
(1, 2399, "Cain looked at her. She looked back.", "Cain looked at her. She didn’t blink."),
(1, 2493, "a wide, ragged line of tissue that looked like it had been melted and reset by someone in a hurry", "a wide, ragged line of tissue, melted and reset by someone in a hurry"),
# --- Book 1 singles ---
(1, 113, "she looked forward to where the prophet walked", "her gaze went forward to where the prophet walked"),
(1, 114, "He looked down at it, then over his shoulder at her.", "He glanced down at it, then over his shoulder at her."),
(1, 228, "Cain looked. His eye tracked to where she pointed", "Cain turned. His eye tracked to where she pointed"),
(1, 347, "The woman looked at him. Tired eyes, cracked lips,", "The woman turned to him. Tired eyes, cracked lips,"),
(1, 403, "Carina sat on her cot and looked around the room.", "Carina sat on her cot and took in the room."),
(1, 447, "She looked up from her bowl with the first real spark of interest", "Her head came up from her bowl with the first real spark of interest"),
(1, 454, "Gormund looked at her. “You’re shopping for an apothecary?”", "Gormund squinted at her. “You’re shopping for an apothecary?”"),
(1, 487, "Then he looked at the smith.", "Then he turned to the smith."),
(1, 547, "crossed her arms and looked at Uthesia with an expression", "crossed her arms and fixed Uthesia with an expression"),
(1, 551, 'Gormund looked up. "You trust it’ll go?"', 'Gormund glanced up. "You trust it’ll go?"'),
(1, 619, "Everyone looked at her. She shrugged.", "Every head turned. She shrugged."),
(1, 813, "The two men looked at each other. Gormund didn’t back down", "The two men locked eyes. Gormund didn’t back down"),
(1, 881, "and Cain looked at that contrast and felt", "and Cain weighed that contrast and felt"),
(1, 903, "Andromalius looked at her. At the blindfold, the robes, the way she stood.", "Andromalius turned to her. The blindfold, the robes, the way she stood."),
(1, 922, "Gormund looked at those doors and failed to prevent himself", "Gormund eyed those doors and failed to prevent himself"),
(1, 1013, "staffed by a single clerk who looked like he’d been awake for days", "staffed by a single clerk visibly awake for days"),
(1, 1029, "Cain looked at him with one dark eye.", "Cain regarded him with one dark eye."),
(1, 1123, "Cain looked at Muse. Muse’s face was unreadable,", "Cain turned to Muse. Muse’s face was unreadable,"),
(1, 1192, "Pulled the spirit back. Looked at Cain.", "Pulled the spirit back. Turned to Cain."),
(1, 1310, "Looked at the blood on his fingers with the expression", "Examined the blood on his fingers with the expression"),
(1, 1315, "Andromalius looked up at them. At the paladin", "Andromalius raised his eyes to them. At the paladin"),
(1, 1340, "He looked at her. She stood with her weight balanced", "He turned to her. She stood with her weight balanced"),
(1, 1345, "She looked at Andromalius, then back at Cain.", "She glanced at Andromalius, then back at Cain."),
(1, 1346, "Cain looked at her for a long time. The girl with nothing in her eyes,", "Cain studied her for a long time. The girl with nothing in her eyes,"),
(1, 1430, "She looked at her left wrist. Already swelling,", "She checked her left wrist. Already swelling,"),
(1, 1489, "He looked at the hammer in his hand. Blunt-headed.", "He weighed the hammer in his hand. Blunt-headed."),
(1, 1495, "Carina looked at him. At the blood on his coat, the pallor of his face, the way he was swaying on his feet. At the hammer in his hand.", "Carina took him in. The blood on his coat, the pallor of his face, the way he was swaying on his feet. The hammer in his hand."),
(1, 1562, "He looked at Cain.", "He raised his eyes to Cain."),
(1, 1586, "Cain looked at her. At the fire on her hands. At the set of her jaw, the straightness of her back,", "Cain took her in. The fire on her hands. The set of her jaw, the straightness of her back,"),
(1, 1589, "Andromalius looked at them. The hammer hung in his good hand,", "Andromalius faced them. The hammer hung in his good hand,"),
(1, 1726, "Uthesia touched her jaw. Looked at Carina. At the tears, the broken hand,", "Uthesia touched her jaw. Took in Carina. The tears, the broken hand,"),
(1, 1735, "She looked up. She couldn’t see them but she turned her face", "Her face came up. She couldn’t see them but she turned"),
(1, 1740, "She looked at Gormund on the floor, at Muse bent over him, at the blood.", "Her eyes went over Gormund on the floor, Muse bent over him, the blood."),
(1, 1876, "Leo looked at him. The exhaustion was there,", "Leo met his stare. The exhaustion was there,"),
(1, 1889, "and looked at Leo with eyes that carried an intelligence", "and considered Leo with eyes that carried an intelligence"),
(1, 1892, "Bael’s messenger looked at the two Lords with an expression", "Bael’s messenger stared at the two Lords with an expression"),
(1, 1941, "He looked at Yoo beside him. She raised an eyebrow.", "He glanced at Yoo beside him. She raised an eyebrow."),
(1, 1966, "Leo looked around the table.", "Leo scanned the table."),
(1, 2010, "Lumina looked at her. The mask gave nothing away,", "Lumina turned to her. The mask gave nothing away,"),
(1, 2054, "She looked at her wrist again.", "She examined her wrist again."),
(1, 2142, "Andromalius looked at the bag for a long time.", "Andromalius stared at the bag for a long time."),
(1, 2153, "Andromalius looked at him.", "Andromalius met his eye."),
(1, 2284, "It looked like the bridge led nowhere.", "It was as if the bridge led nowhere."),
(1, 2392, "Gormund looked at Cain, and Cain gave a single nod.", "Gormund checked with Cain, and Cain gave a single nod."),
(1, 2441, "Gormund’s hands stopped on the reindeer hide. He looked at her.", "Gormund’s hands stopped on the reindeer hide."),
(1, 2453, "He looked up from the carcass.", "He raised his head from the carcass."),
(1, 2508, "Cain looked at the armor on the floor.", "Cain considered the armor on the floor."),
(1, 2645, "Cain looked at Gormund. The dwarf was already pulling", "Cain glanced at Gormund. The dwarf was already pulling"),
(1, 2730, "Cain looked at Uthesia, then at Muse, then back at Uthesia.", "Cain’s eye went from Uthesia to Muse and back."),
(1, 2742, "She looked at him. “Worst case,", "She faced him. “Worst case,"),
(1, 2857, "The woman looked at her for a long moment.", "The woman considered her for a long moment."),
(1, 2864, "and looked at Carina with bright, warm eyes", "and took Carina in with bright, warm eyes"),
(1, 2874, "Carina looked at him. Charming. Confident.", "Carina studied him. Charming. Confident."),
(1, 2918, "She looked at the two of them. The Dragon God and his daughter,", "She regarded the two of them. The Dragon God and his daughter,"),
(1, 2933, "Lumina looked at him.", "Lumina blinked at him."),
]
