# -*- coding: utf-8 -*-
# Permafrost Revision 4 line edits — batch 1: "something that" constructions
# (book, paragraph_index_0based, old_substring, new_substring)
EDITS_B1 = [
(1, 27, "usually about something that made her want to punch him", "usually about whatever made her want to punch him"),
(1, 213, "they’d all be looking for something that might not exist", "they’d all be hunting a threat that might not exist"),
(1, 215, "moved behind something that blocked the noise", "moved behind whatever blocked the noise"),
(1, 333, "his hands shaking from something that wasn’t the cold", "his hands shaking, and not from the cold"),
(1, 427, "smell of porridge and bread and something that might have been actual butter", "smell of porridge and bread and what might have been actual butter"),
(1, 478, "hammering something that glowed orange against an anvil", "hammering metal that glowed orange against an anvil"),
(1, 517, "and she was doing something that Gormund found interesting", "and her behavior caught Gormund’s interest"),
(1, 572, "full packs and something that might have been optimism if Cain squinted at it hard enough", "full packs and what might have been optimism, if Cain squinted at it hard enough"),
(1, 700, "the girl moved like something that had been caged too long and finally found the door open", "the girl moved like an animal caged too long, finally finding the door open"),
(1, 725, "the eyes of something starving, something that had been driven past instinct into desperation", "the eyes of something starving, a creature driven past instinct into desperation"),
(1, 866, "replaced here by something that sounded like a city holding its breath", "replaced here by the sound of a city holding its breath"),
(1, 871, "the eladrin’s voice carried something that sounded like anger held very tightly behind very thin walls", "the eladrin’s voice carried anger held very tightly behind very thin walls"),
(1, 952, "his voice carried something that Muse had never heard from him before", "his voice carried a note Muse had never heard from him before"),
(1, 956, "The room settled into something that wasn’t sleep and wasn’t conversation, just", "The room settled into neither sleep nor conversation, just"),
(1, 1208, "the single eye looking down at him with something that was not yet judgment but could become it", "the single eye fixed on him with what was not yet judgment but could become it"),
(1, 1256, "the leverage required to swing something that heavy", "the leverage required to swing a weapon that heavy"),
(1, 1410, "moving faster than something that large had any right to move", "moving faster than anything that large had any right to move"),
(1, 1459, "and she was running on something that wasn’t going to last", "and she was running on reserves that weren’t going to last"),
(1, 1481, "The two types of dizziness combined into something that made standing up feel like climbing a mountain in a hurricane", "The two types of dizziness combined until standing up felt like climbing a mountain in a hurricane"),
(1, 1488, "Something solid, something that blocked the channel", "Something solid, big enough to block the channel"),
(1, 1531, "raised in something that wasn’t quite a prayer", "raised in what wasn’t quite a prayer"),
(1, 1670, "then something that might have been a laugh if he’d had the air for it", "then what might have been a laugh, if he’d had the air for it"),
(1, 1794, "her body shaking with something that went past anger into a territory that didn’t have a name", "her body shaking with a force that went past anger into a territory that didn’t have a name"),
(1, 1989, "processing something that shouldn’t have been possible", "processing a claim that shouldn’t have been possible"),
(1, 2052, "the potions at least, something that proved she’d been useful", "the potions at least, proof that she’d been useful"),
(1, 2337, "turning the dull steel into something that looked like it had been dipped in sugar", "coating the dull steel until it might have been dipped in sugar"),
(1, 2475, "carried something that wasn’t forgiveness because forgiveness required an offense", "carried what wasn’t forgiveness, because forgiveness required an offense"),
(1, 2504, "the reluctant separation of something that had become part of him", "the reluctant separation of a shell that had become part of him"),
(1, 2715, "where something that was not a bird had learned to sing", "where a thing that was not a bird had learned to sing"),
(1, 2758, "advancing with the deliberate pace of something that intended to stay", "advancing with the deliberate pace of a storm that intended to stay"),
(1, 2805, "holding the lid on something that would consume them if they let it out", "holding the lid on what would consume them if they let it out"),
(1, 2810, "pressed against the cabin walls with the patience of something that had nowhere else to be", "pressed against the cabin walls with the patience of weather that had nowhere else to be"),
(1, 2826, "her body being laid flat on something that was softer than ground", "her body being laid flat on a surface softer than ground"),
]
EDITS_B2 = [
(2, 102, "turned him into something that could face a dragon and win", "turned him into someone who could face a dragon and win"),
(2, 233, "The fabric was spotted with something that could have been blood in better light", "The fabric was spotted with what could have been blood in better light"),
(2, 275, "Thick, dark, the consistency of something that had been partially frozen", "Thick, dark, half-frozen"),
(2, 279, "becoming something that wasn’t a trail anymore but a drag mark", "becoming not a trail anymore but a drag mark"),
(2, 315, "Panic attacks weren’t something that happened to him", "Panic attacks didn’t happen to him"),
(2, 341, "separated by something that had pushed through from inside", "separated by whatever had pushed through from inside"),
(2, 344, "the frantic, total commitment of something that understood it was being killed", "the frantic, total commitment of a creature that understood it was being killed"),
(2, 346, "the grip becoming something mechanical, something that operated independently of the body it was attached to", "the grip becoming something mechanical, a mechanism that operated independently of the body it was attached to"),
(2, 391, "earned by killing something that had been hunting them since Velldale", "earned by killing the thing that had been hunting them since Velldale"),
(2, 406, "trying to organize into something that made sense", "trying to organize into a system that made sense"),
(2, 448, "settling behind her eyes with the intensity of something that was not going to improve without rest she didn’t have", "settling behind her eyes with the intensity of a wound that was not going to improve without rest she didn’t have"),
(2, 496, "the frame protesting the terrain with the creaking complaints of something that had never been designed for this", "the frame protesting the terrain with the creaking complaints of a tool never designed for this"),
(2, 577, "coated in frost that turned the military vessel into something that looked carved from ice itself", "coated in frost that turned the military vessel into a sculpture carved from ice itself"),
(2, 593, "now she was standing inside something that hummed with an engineering philosophy", "now she was standing inside a structure that hummed with an engineering philosophy"),
(2, 731, "a motor or a flywheel or something that required rotational energy", "a motor or a flywheel, machinery that required rotational energy"),
(2, 750, "The stride of something that had been built to move the way soldiers moved", "A stride built to move the way soldiers moved"),
(2, 835, "a small rupture in something that felt like it could be a main artery or one of its branches", "a small rupture in what felt like a main artery or one of its branches"),
(2, 861, "being suspended in something that wasn’t air and wasn’t liquid", "being suspended in matter that wasn’t air and wasn’t liquid"),
(2, 1049, "the furnace dominated the space with the authority of something that had been built to produce power", "the furnace dominated the space with the authority of a machine built to produce power"),
(2, 1105, "arranged with the careful packing of something that was meant to arrive intact", "arranged with the care of cargo meant to arrive intact"),
(2, 1142, "radiated the quiet smugness of something that had been built to withstand exactly this", "radiated the quiet smugness of a door built to withstand exactly this"),
(2, 1258, "the charming intellectual replaced by something that operated at a lower, colder temperature", "the charming intellectual replaced by a mind that operated at a lower, colder temperature"),
(2, 1298, "replaced by something that wasn’t summer but wasn’t winter either", "replaced by warmth that wasn’t summer but wasn’t winter either"),
(2, 1370, "shouting something that the wind stole before it reached shore", "shouting words the wind stole before they reached shore"),
(2, 1408, "the patient determination of something that had learned it could wait", "the patient determination of a hunter that had learned it could wait"),
(2, 1417, "into something quieter, something that had stopped fighting the circumstances", "into something quieter, a stillness that had stopped fighting the circumstances"),
(2, 1426, "The weight of having done something that the person beside you didn’t agree with", "The weight of having done what the person beside you didn’t agree with"),
(2, 1426, "to become something that wouldn’t be noticed until the storm passed", "to make herself unnoticeable until the storm passed"),
(2, 1522, "driven out of him by something that operated at a level below what anyone in the crowd could see", "driven out of him by a force that operated at a level below what anyone in the crowd could see"),
(2, 1523, "settled into the snow with the quiet finality of something that had been emptied", "settled into the snow with the quiet finality of a vessel that had been emptied"),
(2, 1589, "his voice dropping to something that was barely a whisper and entirely a promise", "his voice dropping to what was barely a whisper and entirely a promise"),
(2, 1636, "the tower growing from a needle to a pillar to something that dominated the sky", "the tower growing from a needle to a pillar to a presence that dominated the sky"),
(2, 1728, "the cold pressed inward with the patience of something that knew it would eventually win", "the cold pressed inward, patient, certain it would eventually win"),
(2, 1899, "She felt something that might have been pity", "She felt what might have been pity"),
(2, 1906, "compressed by experience into something that read as dangerous on an instinctual level", "compressed by experience into a weight that read as dangerous on an instinctual level"),
(2, 1909, "mass accumulated through a lifetime of swinging something that heavy", "mass accumulated through a lifetime of swinging steel that heavy"),
(2, 1915, "the momentary lag of two professionals processing something that didn’t fit the pattern", "the momentary lag of two professionals processing a sight that didn’t fit the pattern"),
(2, 1926, "turning flesh and bone into something that functioned like armor", "until flesh and bone functioned like armor"),
(2, 1970, "had been locked by something that wasn’t ki and wasn’t magic and wasn’t physical restraint", "had been locked by a force that wasn’t ki and wasn’t magic and wasn’t physical restraint"),
(2, 1978, "the predator’s edge softened into something that was almost kind", "the predator’s edge softened into a warmth that was almost kind"),
(2, 2156, "the unfocused stare of a woman looking at something that isn’t in the room", "the unfocused stare of a woman fixed on what isn’t in the room"),
(2, 2225, "the small throat-clear that meant he was about to say something that mattered", "the small throat-clear that meant his next words mattered"),
(2, 2367, "the fabric treated with something that made it hang differently", "the fabric treated until it hung differently"),
(2, 2493, "compressed by time and urgency into something that resembled sedimentary rock more than filing", "compressed by time and urgency into strata closer to sedimentary rock than filing"),
(2, 2548, "a natural formation that led down into something that had been buried and forgotten for centuries", "a natural formation that led down into what had been buried and forgotten for centuries"),
(2, 2815, "the fondness joined by something that might have been duty", "the fondness joined by what might have been duty"),
(2, 2841, "the channels that had been empty for months flooding with something that was not Naika’s light but was light nonetheless", "the channels that had been empty for months flooding with light that was not Naika’s but was light nonetheless"),
(2, 3034, "fast for something that size", "fast for a creature that size"),
(2, 3787, "The sound of a fist going through something that had been a piece of furniture", "The sound of a fist going through what had been a piece of furniture"),
(2, 3873, "the mystery calcifying into something that occupied a permanent partition of his attention", "the mystery calcifying into a fixation that occupied a permanent partition of his attention"),
(2, 4114, "Pushed aside by something that was louder and more immediate", "Pushed aside by an alarm that was louder and more immediate"),
(2, 4447, "staring up into Barbatos’s face with something that terrified him", "staring up into Barbatos’s face with a will that terrified him"),
(2, 4514, "replaced by something harder, something that had been calcifying for years", "replaced by something harder, a verdict that had been calcifying for years"),
]
EDITS = EDITS_B1 + EDITS_B2
