# -*- coding: utf-8 -*-
# Revision 6 edits — Part A: dialogue/thought tag punctuation + "wasn't A, it was B"
# (book, paragraph_index, old, new)
EDITS = [
# ---- Book 1: period→comma before tags; lowercase pronouns after !/? ----
(1, 82, "“I didn’t say I was going to do it for free.” Carina shot back", "“I didn’t say I was going to do it for free,” Carina shot back"),
(1, 152, "“Dried meat and hard bread.” Gormund cut in", "“Dried meat and hard bread,” Gormund cut in"),
(1, 236, "“Or it’s a farmhouse with food and information.” Carina shot back.", "“Or it’s a farmhouse with food and information,” Carina shot back."),
(1, 261, "‘Enough.’ She told herself.", "‘Enough,’ she told herself."),
(1, 535, "“You’ve never had a fair fight in your life.” Gormund cut in.", "“You’ve never had a fair fight in your life,” Gormund cut in."),
(1, 564, "“Another round of stew?” She asked the table.", "“Another round of stew?” she asked the table."),
(1, 797, "“Cain.” She said more quietly,", "“Cain,” she said more quietly,"),
(1, 842, "“She wants to be sent scouting again.” Gormund translated", "“She wants to be sent scouting again,” Gormund translated"),
(1, 1162, "“Skill.” Uthesia corrected.", "“Skill,” Uthesia corrected."),
(1, 1242, "“CAIN!” She screamed.", "“CAIN!” she screamed."),
(1, 1258, "‘He did that on purpose.’ Uthesia realized,", "‘He did that on purpose,’ Uthesia realized,"),
(1, 1418, "‘It’s not even pressing hard.’ She realized", "‘It’s not even pressing hard,’ she realized"),
(1, 1443, "‘Get up.’ He told himself.", "‘Get up,’ he told himself."),
(1, 1544, "‘She’s keeping me in this.’ Cain realized", "‘She’s keeping me in this,’ Cain realized"),
(1, 1859, "“The theological implications are yours to worry about.” Yara cut in.", "“The theological implications are yours to worry about,” Yara cut in."),
(1, 2025, "‘It’s still true.’ She decided,", "‘It’s still true,’ she decided,"),
(1, 2177, "‘Could be anything.’ He told himself.", "‘Could be anything,’ he told himself."),
(1, 2228, "“Could have been anyone.” Uthesia finished.", "“Could have been anyone,” Uthesia finished."),
(1, 2573, "‘Everyone respects each other here.’ He told her,", "‘Everyone respects each other here,’ he told her,"),
(1, 2679, "“Scout the interior.” She told it.", "“Scout the interior,” she told it."),
(1, 2769, "“Careful.” Uthesia finished.", "“Careful,” Uthesia finished."),
(1, 2846, "“When you cleaned me.” Carina clarified,", "“When you cleaned me,” Carina clarified,"),
(1, 3015, "“I’m motivated.” He corrected.", "“I’m motivated,” he corrected."),
# ---- Book 2 ----
(2, 253, "“GET INSIDE.” Uthesia screamed over the wind.", "“GET INSIDE,” Uthesia screamed over the wind."),
(2, 303, "“STOP.” Uthesia screamed.", "“STOP,” Uthesia screamed."),
(2, 356, "“LET GO!” She screamed,", "“LET GO!” she screamed,"),
(2, 371, "“WHERE IS CAIN?” She screamed.", "“WHERE IS CAIN?” she screamed."),
(2, 423, "‘It’s just annoying.’ She decided.", "‘It’s just annoying,’ she decided."),
(2, 623, "“What’s that about?” She asked Jane,", "“What’s that about?” she asked Jane,"),
(2, 669, "‘Just explain it.’ She told herself.", "‘Just explain it,’ she told herself."),
(2, 1461, "“ARE YOU DONE?” He screamed.", "“ARE YOU DONE?” he screamed."),
(2, 1492, "“NO MORE FIGHTING!” She bellowed,", "“NO MORE FIGHTING!” she bellowed,"),
(2, 1612, "“Or trapped somewhere along the river.” Elizabeth finished,", "“Or trapped somewhere along the river,” Elizabeth finished,"),
(2, 1675, "“The doors ate your ki last time.” Billy pointed out,", "“The doors ate your ki last time,” Billy pointed out,"),
(2, 1849, "“Approximately.” She suggested.", "“Approximately,” she suggested."),
(2, 2568, "“Can you capture that thing?” He asked Uthesia.", "“Can you capture that thing?” he asked Uthesia."),
(2, 2607, "“IT’S DOWN! TAKE IT!” He called upward.", "“IT’S DOWN! TAKE IT!” he called upward."),
(2, 2654, "you guys are always so cold to me.” Carina mumbled", "you guys are always so cold to me,” Carina mumbled"),
(2, 3020, "“Stay behind me!” He ordered,", "“Stay behind me!” he ordered,"),
(2, 3117, "“How many more can I do?” She asked the air beside her.", "“How many more can I do?” she asked the air beside her."),
(2, 3195, "“FIND THE CASTER!” He bellowed,", "“FIND THE CASTER!” he bellowed,"),
(2, 3466, "‘It’s been a thousand years.’ He told himself.", "‘It’s been a thousand years,’ he told himself."),
# ---- Book 1: "wasn't A, it was B" rewrites ----
(1, 395, "Then he exhaled, and it wasn’t relief, it was the sound of a man moving a piece on a board", "Then he exhaled, and the sound was of a man moving a piece on a board"),
(1, 618, "and it wasn’t pessimism. It was just the truth, stated plainly", "and there was no pessimism in it. Just the truth, stated plainly"),
(1, 767, "That last part wasn’t directed at her. It was directed at everyone, but", "That last part was directed at everyone, but"),
(1, 816, "Two hours wasn’t enough to cure them properly. It wasn’t enough to do anything properly.", "Two hours wasn’t enough to cure them properly, or to do anything properly."),
(1, 961, "The frustration on her face wasn’t the hot, explosive kind she usually wore. It was colder.", "The frustration on her face was colder than the hot, explosive kind she usually wore."),
(1, 1501, "The throw wasn’t pretty. It wasn’t the compact, vicious accuracy that had deflected the bell mallet earlier that night.", "The throw wasn’t pretty, had none of the compact, vicious accuracy that had deflected the bell mallet earlier that night."),
(1, 1528, "It wasn’t sight. It was the world stripped down to weight and movement, and", "The world, stripped down to weight and movement, and"),
(1, 1588, "The hit wasn’t clean. It wasn’t trained.", "The hit was neither clean nor trained."),
(1, 1611, "It wasn’t elegant. It wasn’t coordinated precision as much as it was desperate improvisation.", "It wasn’t elegant, more desperate improvisation than coordinated precision."),
(1, 1801, "The healing wasn’t warm. It wasn’t the golden, steady flow she remembered from her prime", "The healing came without warmth, nothing of the golden, steady flow she remembered from her prime"),
(1, 2330, "The cold wasn’t coming from any direction. It was ambient, total, pressed into the air itself", "The cold came from no direction at all, ambient, total, pressed into the air itself"),
]
