# -*- coding: utf-8 -*-
# Revision 6 edits — Part B: Book 1 "Not X. Y." reduction (cut/reword the non-load-bearing)
EDITS = [
(1, 15, "Muse couldn’t finish that thought. Not even privately.", "Muse couldn’t finish that thought, even privately."),
(1, 281, "Not the broken rocky terrain of the afternoon. She could move faster on this without risking a fall", "She could move faster on this without risking a fall"),
(1, 309, "Not annoyed, not exasperated, not the usual grumbling tolerance. Something sharper.", "None of the usual grumbling tolerance. Something sharper."),
(1, 336, "Not at them, not exactly, but close enough that the message was clear.", "Close enough to them that the message was clear."),
(1, 345, "Not a surprise, she was past surprise, but the weary recognition of another number being added to a list that was already too long.", "She was past surprise. What moved there was the weary recognition of another number being added to a list that was already too long."),
(1, 494, "Not a good one, the balance was off and the steel was mediocre, but the shape was right.", "A poor one, the balance off and the steel mediocre, but the shape was right."),
(1, 533, "Not about the mission. Not about the road or the cold or the supplies or what waited to the west.", "Not about the mission, or the road, or the cold, or what waited to the west."),
(1, 627, "Not by much, but enough that Muse noticed.", "Only a little, but enough that Muse noticed."),
(1, 675, "Not quite a laugh, not quite a breath, something in between that lived in the back of her throat", "Something between a laugh and a breath, a thing that lived in the back of her throat"),
(1, 686, "Not close enough to be immediate, but close enough that the difference was measurable.", "Still distant, but close enough that the difference was measurable."),
(1, 704, "Not dramatically, not the killing cold of the deep interior, but enough that the landscape had changed character.", "Subtly, nothing like the killing cold of the deep interior, but enough that the landscape had changed character."),
(1, 725, "Its eyes were wrong. Not the placid, calculating gaze of a predator assessing prey. These were the eyes", "Its eyes were wrong, empty of the placid calculation of a predator assessing prey. These were the eyes"),
(1, 752, "Not clean, not elegant, nothing about killing a beast this big could be elegant, but", "Killing a beast this big allowed for neither clean nor elegant, but"),
(1, 805, "Not rot, not disease exactly, but a degradation", "Neither rot nor disease exactly, but a degradation"),
(1, 849, "Not the city itself, not the smoke and salt and human density she’d come to associate with large settlements. This was something else.", "Nothing of the smoke and salt and human density she’d come to associate with large settlements. This was something else."),
(1, 852, "His voice had changed. Not the calm, measured tone of the road. Something harder.", "His voice had changed, gone harder than the calm, measured tone of the road."),
(1, 920, "Not the kind he usually needed, the slow, steady, background kind that kept the edges soft and the memories manageable. This was the sharp kind.", "A different kind from the usual slow, steady, background drinking that kept the edges soft and the memories manageable. This was the sharp kind."),
(1, 981, "the answer would have destroyed him. Not the answer itself. His own reaction to it.", "the answer would have destroyed him. Or rather, his reaction to it would have."),
(1, 996, "He couldn’t be this. Not here, not now, not when they’d finally started to feel like something worth protecting.", "He couldn’t be this, here, now, when they’d finally started to feel like something worth protecting."),
(1, 1035, "that she didn’t have an answer. Not because Carina was right about everything. But because the thing she was right about", "that she didn’t have an answer, not because Carina was right about everything, but because the thing she was right about"),
(1, 1061, "This was the part she’d been waiting for. Not the deliberation, not the hand-wringing, not the process. The job.", "This was the part she’d been waiting for, past the deliberation, the hand-wringing, the process. The job."),
(1, 1169, "Not deliberately. Not with any plan or strategy or the prophet’s careful wisdom.", "Without meaning to, without any plan or strategy or the prophet’s careful wisdom."),
(1, 1228, "Not a calculated laugh for effect. A genuine laugh, the kind", "A genuine laugh, nothing calculated in it, the kind"),
(1, 1278, "Not the whole fight. The first few seconds.", "Only the first few seconds."),
(1, 1315, "Not the injuries, not the position, not the tactical assessment that ran automatically in the back of his skull like a second heartbeat. The other thing.", "Setting aside the injuries, the position, the tactical assessment that ran automatically in the back of his skull like a second heartbeat. The other thing."),
(1, 1330, "She was reading him. Not his face, not his expression. His body.", "She was reading him. Skipping the face, the expression. His body."),
(1, 1352, "Not the cold of the dome, not the cold of the frost or the wind or the dying world above them. A different cold.", "A different cold from the dome’s, from the frost and the wind and the dying world above them."),
(1, 1358, "Not pain. Not the ribs or the blood or the bruised lung or the exhaustion.", "Past pain, past the ribs and the blood and the bruised lung and the exhaustion."),
(1, 1393, "Not panic. A mechanical adjustment, the same recalibration", "No panic in it, just a mechanical adjustment, the same recalibration"),
(1, 1415, "There was no technique for that. Not at this level of force, not with her ki already depleted from two consecutive redirections.", "There was no technique for that, at this level of force, with her ki already depleted from two consecutive redirections."),
(1, 1481, "He started moving. Not running, he couldn’t run, his legs weren’t capable of running.", "He started moving. Running was beyond him, beyond what his legs could give."),
(1, 1489, "They moved together. Not a plan, not a coordinated strategy, just two people", "They moved together, no plan, no coordinated strategy, just two people"),
(1, 1512, "Not gracefully, not the controlled descent of a fighter choosing to rest. She fell,", "Without grace, without the controlled descent of a fighter choosing to rest. She fell,"),
(1, 1566, "Not smoothly, and not with the prophet’s composure. She stood the way", "Without smoothness, without the prophet’s composure. She stood the way"),
(1, 1571, "Her fists burned. Not bright, not blinding. A low, steady flame that wrapped around her knuckles", "Her fists burned, low and quiet, a steady flame that wrapped around her knuckles"),
(1, 1590, "Not the controlled, amused sounds he’d been making throughout the fight. A real scream,", "Nothing like the controlled, amused sounds he’d been making throughout the fight. A real scream,"),
(1, 1613, "Not deep, there wasn’t enough force left for deep, but enough to bleed, enough to matter.", "Shallow, there wasn’t enough force left for deep, but enough to bleed, enough to matter."),
(1, 1638, "Not the servants, not the dragon. Voices she knew, raised and raw", "Voices she knew, raised and raw"),
(1, 1663, "Not stopped, but steadied enough.", "Still trembling, but steadied enough."),
(1, 1713, "Not rage, not defiance. The raw, involuntary sound", "Neither rage nor defiance. The raw, involuntary sound"),
(1, 1747, "Not because he was less afraid. Because his hands had been trained to be steady", "He was no less afraid. His hands had simply been trained to be steady"),
(1, 1805, "Not what he said, just his voice, the sound of it, loud and sharp", "His voice more than the words, the sound of it, loud and sharp"),
(1, 1810, "Not the cruel warmth of Andromalius’s bedchamber, the obscene heat of stolen wood burning for one man’s comfort. Real warmth.", "None of the cruel warmth of Andromalius’s bedchamber, the obscene heat of stolen wood burning for one man’s comfort. Real warmth."),
(1, 1874, "Not voluntarily, not by choice, but by the instinct that was bred into", "By reflex rather than choice, the instinct bred into"),
(1, 1875, "Not out of disrespect. Because the half-second delay was the only rebellion", "Disrespect had nothing to do with it. The half-second delay was the only rebellion"),
(1, 1895, "Not anger, exhaustion finding a new shape.", "Less anger than exhaustion finding a new shape."),
(1, 1901, "Not consciously, no more conscious than shifting languages", "Unconsciously, no more deliberate than shifting languages"),
(1, 1973, "Not because he’d raised his voice, but because he’d directed it", "Less because he’d raised his voice than because he’d directed it"),
(1, 1979, "Not the political quiet of the summit tent, where silence meant calculation. This was the genuine quiet", "None of the political quiet of the summit tent, where silence meant calculation. This was the genuine quiet"),
(1, 2029, "Not fully. A jagged edge of white", "Partway. A jagged edge of white"),
(1, 2099, "Not just stocked, full, the shelves packed tight", "Beyond stocked, full, the shelves packed tight"),
(1, 2103, "Not silence, exactly. The functional quiet of two people working a job,", "Quiet, but the functional kind, two people working a job,"),
(1, 2104, "Not because she wanted to, but because the question had been pressing", "Less because she wanted to than because the question had been pressing"),
(1, 2127, "Not generous, not cruel. Functional.", "Neither generous nor cruel. Functional."),
(1, 2250, "Not dramatically, but enough that the ground crunched differently underfoot", "Only by degrees, but enough that the ground crunched differently underfoot"),
(1, 2252, "Not a lot, not the running commentary Carina had provided, but she offered", "Only a little, never the running commentary Carina had provided, but she offered"),
(1, 2262, "Not the hollowed-out emptiness of Valdara, where people had hidden behind doors and shuttered windows. This was complete.", "Beyond even the hollowed-out emptiness of Valdara, where people had hidden behind doors and shuttered windows. This was complete."),
(1, 2351, "Not warm in the traditional sense, but the absence of the open air", "Hardly warm in the traditional sense, but the absence of the open air"),
(1, 2439, "Not comfortable, but livable.", "Short of comfortable, but livable."),
(1, 2567, "They were racing. Not really racing, the way you race a train from a car window, her mother jogging", "They were racing, or racing the way you race a train from a car window, her mother jogging"),
(1, 2614, "Not by choice, the angle of her head made it swallow or choke", "The angle of her head made it swallow or choke"),
(1, 2748, "Not the slow, heavy drift of snowfall. A wall of wind and ice", "A wall of wind and ice"),
(1, 2759, "Not by choice, by necessity.", "By necessity rather than choice."),
(1, 2790, "Not accusation. Observation.", "Flat, level, no charge in it."),
(1, 2823, "Not rough, not gentle, efficient.", "Neither rough nor gentle, efficient."),
(1, 2832, "Not the foggy half-consciousness of the last few days. Actual waking, the world arriving in focus", "Actual waking this time, the world arriving in focus"),
(1, 2872, "Not the soft version, not the edited version she might have given Muse or Cain. The real version, the Carina version, delivered", "The real version, the Carina version, none of the softening or editing she might have given Muse or Cain, delivered"),
(1, 2897, "Not a question, not really. She’d asked it three times", "Barely a question. She’d asked it three times"),
]
